# Site Settings
name: Idvogados
title: Idvogados
<<<<<<< HEAD
description: Plataforma gratuita conectando trabalhadores e advogados.
# email: contato@idvogados.org
email: parceiro.idvogados@gmail.com
disqus_username: idvogados
=======
description: Projeto de acesso à justiça.
>>>>>>> 775d413392719bc014c3abcfafe6e850fba37ec2
link-anchor:
  - title: Home
    url: /
link-button:
  - title: Quero Colaborar
    url: https://linktr.ee/idvogados
link-footer:
  - title: Termos de Uso
    url: /termos-de-uso/
  - title: Imprint
    action: window.print()
email: contato@idvogados.org
disqus_username: idvogados
copyright-year: 2020

# Social Media Settings
# Remove the item if you don't need it
github_username: idvogados
facebook_username: idvogados
twitter_username: idvogados_ofc
<<<<<<< HEAD
instagram_username: projeto_idvogados
linkedin_username: idvogados
medium_username: idvogados
=======
instagram_username: idvogados.ofc
linkedin_username: idvogados-org
>>>>>>> 775d413392719bc014c3abcfafe6e850fba37ec2

# Posts Settings
show_modal_on_exit: true

# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://idvogados.org" # the base hostname & protocol for your site
google_analytics: "G-DTG3FDMY4V"
language: "pt-BR"

# Pagination Settings
paginate_path: "/page/:num/"
pagination:
  per_page: 6
  permalink: "/page/:num/"
  title: " - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true

# Build settings
# paginate: 5
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
categories_folder: category

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate-v2
  - jekyll-paginate-content

# Exclude my node related stuff
exclude:
  [
    "package.json",
    "package-lock.json",
    "src",
    "node_modules",
    "initpost.sh",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "README.md",
  ]
